num_classes: 2
save_dir: save_0912
seed: 123
device: cuda

lr: 0.005
ratio: 0.3

train_mode: cons_unlab # vat, cons_unlab, cat
weight_epoch: 15

weights:
  cons_weight: 0.5
  weight_adv: 0.001
  weight_cons: 0.05



