device: cpu
lr: 0.001
num_classes: 2
ratio: 0.1
save_dir: save_0913/lower_201lr_10lab
seed: 123
train_mode: cons_unlab
weight_epoch: 100
weights:
  cons_weight: 0.5
  weight_adv: 0.001
  weight_cons: 0.05
